server:
  port: 8080

spring:
  application:
    name: iot-agent-alert-api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
